using System;
using System.Reflection;
using System.Runtime.InteropServices;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: ComVisibleAttribute(false)]
[assembly: CLSCompliantAttribute(true)]
[assembly: AssemblyTitleAttribute("your product")]
[assembly: AssemblyDescriptionAttribute("A suite of CLI Applications")]
[assembly: AssemblyConfigurationAttribute("release")]
[assembly: AssemblyCompanyAttribute("www.yourcompany.com")]
[assembly: AssemblyProductAttribute("your product")]
[assembly: AssemblyCopyrightAttribute("Copyright (C) 2013 your company ")]
[assembly: AssemblyTrademarkAttribute("")]
[assembly: AssemblyCultureAttribute("")]
[assembly: AssemblyVersionAttribute("1.0.0.0")]
[assembly: AssemblyInformationalVersionAttribute("1.0.0")]

